-- 1. Tabel Baru: villages (Master Desa)
CREATE TABLE IF NOT EXISTS `villages` (
  `id_village` INT PRIMARY KEY AUTO_INCREMENT,
  `village_code` VARCHAR(10) NOT NULL UNIQUE COMMENT 'Kode internal desa, misal: V001',
  `village_name` VARCHAR(100) NOT NULL COMMENT 'Nama lengkap desa',
  `village_abbr` VARCHAR(5) NOT NULL UNIQUE COMMENT 'Singkatan untuk Place Code, misal: NJ, SW, PR',
  `description` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Master data desa untuk budget allocation';

-- Seed Data Villages
INSERT IGNORE INTO `villages` (`village_code`, `village_name`, `village_abbr`, `description`) VALUES
('V001', 'Nanga Jemah', 'NJ', 'Desa Nanga Jemah'),
('V002', 'Sri Wangi', 'SW', 'Desa Sri Wangi'),
('V003', 'Penepian Raya', 'PR', 'Desa Penepian Raya'),
('V004', 'Tanjung Jaya', 'TJ', 'Desa Tanjung Jaya'),
('V005', 'Riam Jaya', 'RJ', 'Desa Riam Jaya');

-- 2. Tabel Baru: project_code_budgets (Budget per Exp & Place Code per Desa)
CREATE TABLE IF NOT EXISTS `project_code_budgets` (
  `id_budget` INT PRIMARY KEY AUTO_INCREMENT,
  `kode_proyek` VARCHAR(50) NOT NULL,
  `id_village` INT NOT NULL,
  `exp_code` VARCHAR(20) NOT NULL COMMENT 'Expense code, misal: 10101, 20208',
  `place_code` VARCHAR(50) NOT NULL COMMENT 'Format: [exp_code]-[village_abbr]-01, generated by PHP',
  `budget_usd` DECIMAL(15,2) DEFAULT 0.00 COMMENT 'Budget dalam USD',
  `budget_idr` DECIMAL(15,2) DEFAULT 0.00 COMMENT 'Budget dalam IDR',
  `used_usd` DECIMAL(15,2) DEFAULT 0.00 COMMENT 'Budget terpakai (USD)',
  `used_idr` DECIMAL(15,2) DEFAULT 0.00 COMMENT 'Budget terpakai (IDR)',
  `remaining_usd` DECIMAL(15,2) GENERATED ALWAYS AS (`budget_usd` - `used_usd`) STORED,
  `remaining_idr` DECIMAL(15,2) GENERATED ALWAYS AS (`budget_idr` - `used_idr`) STORED,
  `exrate` DECIMAL(10,4) DEFAULT 1.0000 COMMENT 'Exchange rate USD to IDR',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`kode_proyek`) REFERENCES `proyek`(`kode_proyek`) ON DELETE CASCADE,
  FOREIGN KEY (`id_village`) REFERENCES `villages`(`id_village`) ON DELETE RESTRICT,
  UNIQUE KEY `unique_budget_per_village` (`kode_proyek`, `id_village`, `exp_code`),
  INDEX `idx_place_code` (`place_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Budget allocation per exp code per village';

-- 3. Tabel Baru: proposal_budget_details (Budget Detail di Proposal)
CREATE TABLE IF NOT EXISTS `proposal_budget_details` (
  `id_detail` INT PRIMARY KEY AUTO_INCREMENT,
  `id_proposal` INT NOT NULL,
  `id_village` INT NOT NULL,
  `exp_code` VARCHAR(20) NOT NULL,
  `place_code` VARCHAR(50) NOT NULL COMMENT 'Auto-filled dari project_code_budgets',
  `requested_usd` DECIMAL(15,2) DEFAULT 0.00,
  `requested_idr` DECIMAL(15,2) DEFAULT 0.00,
  `currency` VARCHAR(10) DEFAULT 'USD' COMMENT 'Currency proposal: USD atau IDR',
  `exrate` DECIMAL(10,4) DEFAULT 1.0000 COMMENT 'Exchange rate saat proposal dibuat',
  `description` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`id_proposal`) REFERENCES `proposal`(`id_proposal`) ON DELETE CASCADE,
  FOREIGN KEY (`id_village`) REFERENCES `villages`(`id_village`) ON DELETE RESTRICT,
  INDEX `idx_proposal_budget` (`id_proposal`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Budget details per proposal';

-- 4. Update Tabel: proposal
ALTER TABLE `proposal` 
ADD COLUMN `total_budget_usd` DECIMAL(15,2) DEFAULT 0.00 AFTER `file_budget`,
ADD COLUMN `total_budget_idr` DECIMAL(15,2) DEFAULT 0.00 AFTER `total_budget_usd`,
ADD COLUMN `currency` VARCHAR(10) DEFAULT 'USD' AFTER `total_budget_idr`,
ADD COLUMN `exrate_at_submission` DECIMAL(10,4) DEFAULT 1.0000 COMMENT 'Exchange rate saat submit proposal' AFTER `currency`;
